### ISSUE TITLE
Load model error

### ISSUE THREAD

**Issue by pedowii** [OpenMatch/NeuScraper#10]
I've  cloned  model from  https://huggingface.co/OpenMatch/neuscraper-v1-clueweb ,   change model_path to   the real path of  "sentencepiece.bpe.model"  ,  and try  to run with  command :

`uvicorn app:app --reload --host 0.0.0.0 --port 1688`

and then encounter the following exception 
`
  File "/root/miniforge3/envs/pyneuscraper/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniforge3/envs/pyneuscraper/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
`

Did i do anything wrong?  Could you please help  me solve the problem .   Many thanks

**Comment by Pab1x** [comment]
Model weights are included in training_state_checkpoint.tar, not sentencepiece.bpe.model.

**Comment by Pab1x** [comment]
This issue seems to have been resolved.
