### ISSUE TITLE
Example on how to use for a single HTML string?

### ISSUE THREAD

**Issue by tingofurro** [OpenMatch/NeuScraper#3]
Very cool work!

The model you propose seems like it'll be useful to many!
I wonder if you could help create a simple example of how to process a simple HTML string into clean document text.
It seems like the inference.sh script is focused on eval scripts, which assume batching/tokenization, and isn't trivial to use on a single example.

Imagine we have:

```
HTML_str = "<html><article>This is the article content</article></html>"

article_clean_content = call_function(HTML_str)
print(article_clean_content) # This is the article content
```

I feel like that'd be useful in getting people (including me) to use the model!

**Comment by Pab1x** [comment]
Hi, Philippe.

You're right, I seem to have overlooked support for single pages. This is a Great idea and easy to implement, I'll give a new version in the near future with the features you want!

**Comment by nldxtd** [comment]
I tried to replace the `html_content` in build.py with pure html string instead of a commoncrawl dataset in warc format, and was succeed in the encode stage, but when i run commoncrawl.sh, this stage failed and I have no idea over that.

**Comment by nldxtd** [comment]
I also have another question, when you save_predictions, why do you only store the node under Primary task

**Comment by Pab1x** [comment]
> I tried to replace the `html_content` in build.py with pure html string instead of a commoncrawl dataset in warc format, and was succeed in the encode stage, but when i run commoncrawl.sh, this stage failed and I have no idea over that.

Please wait for our adaptation of single web pages!

**Comment by Pab1x** [comment]
> I also have another question, when you save_predictions, why do you only store the node under Primary task

Because we only need the Primary content of the page.

**Comment by Pab1x** [comment]
Hi guys, long time no see, I updated the deployment code for neuscraper. This should do the trick for this requirement by way of port calls. Soon I will write some tutorials about it.

**Comment by tingofurro** [comment]
I'll check it out soon, thanks again @Pab1x !!
