### ISSUE TITLE
Could you add the AnnotateHtml.proto file?

### ISSUE THREAD

**Issue by lihuibng** [OpenMatch/NeuScraper#5]
Could you add the AnnotateHtml.proto file?

**Comment by Pab1x** [comment]
Hi, @lihuibng 
No, I can't provide it, in fact I don't have the "AnnotateHtml.proto" file. 
I think your question should be asked under ClueWeb22 (https://github.com/lemurproject/ClueWeb22), not NeuScraper.
I hope my answer helps.

**Comment by lihuibng** [comment]
got it
