### ISSUE TITLE
data/test/TestNodes.json not found

### ISSUE THREAD

**Issue by lurenss** [OpenMatch/NeuScraper#6]
Hi guys,

I'm investing into the possibility to use NeuScraper for an open source software for which I'm contributing ([ScrapeGraphAI](https://github.com/VinciGit00/Scrapegraph-ai))

Can you provide an example of TestNodes.json?

**Comment by Pab1x** [comment]
Hi, Lorenzo.

data/test/TestNodes.json was generated using step 2 of the Reproduction subsection of the README.
If you have any other questions, please feel free to let me know!

**Comment by Permafacture** [comment]
This is related to #3 in that this repo doesn't provide any documentation on how to use this model except if you download the 10 billion document clueweb22 dataset. An example of how to use this in a more general way would be very helpful
